### PR TITLE
[RETINA-191] History Page

### PR DESCRIPTION
**Pull request by Jbcampbe**
Closes #266 

Not optimized for mobile or tablet. will do that in later PR

### CODE REVIEW

**Comment by ekraihan** [comment]
A loading icon for when tool history is loading might be cool?

**Comment by ekraihan** [comment]
Idea: maybe you could put some kind of split between tool id chunks of the table?

**Comment by ekraihan** [comment]
I noticed that a double calendar pops up... Guessing thats not intentional

This is a small detail, but I noticed that the calendar pops up on a mouseover basis and for me thats a little suprising, and then frustrating when I go to click it and, just before I click it, it pops up because of the mouseover, and then I click it and that makes it dissapear. Make any sense? I wondered if it could be clickable versus mouseover? Maybe the add/update tool calendars as well?

**Comment by ekraihan** [comment]
On the add/update tools page, it is kinda suprising when I move my mouse up to fill in a field field, my mouse goes over the purchased-date field, and the calendar pops up, covering some of the fields.

**Comment by Jbcampbe** [comment]
> I noticed that a double calendar pops up... Guessing thats not intentional

the double calendar was intentional. Since you are picking a datespan I thought it would make selecting beginning and ending dates in different months easier. If it is confusing I can easily remove it

**Comment by Jbcampbe** [comment]
> maybe you could put some kind of split between tool id chunks of the table?

sorry I didn't understand this one

**Pull request merged**
